server.port=64
spring.application.name=laporan-service

# MongoDB Connection Configuration
spring.data.mongodb.uri=mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_laporan?retryWrites=true&w=majority
spring.data.mongodb.database=db_ws_klinik_laporan

spring.mongodb.uri=mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_laporan?retryWrites=true&w=majority
spring.mongodb.database=db_ws_klinik_laporan
