spring:
  application:
    name: jadwal-service

app:
  firebase:
    config-path: classpath:serviceAccountKey.json
    database-id: ws-kliniktest

server:
  port: 63
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:90/eureka}
  instance:
    prefer-ip-address: true