server:
  port: 62

spring:
  application:
    name: resep-service
  data:
    mongodb:
      uri: mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_resep?retryWrites=true&w=majority
      database: db_ws_klinik_resep
  mongodb:
    uri: mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_resep?retryWrites=true&w=majority
    database: db_ws_klinik_resep

eureka:
  client:
    service-url:
      defaultZone: http://localhost:90/eureka
  instance:
    prefer-ip-address: true
