server.port=62
spring.application.name=resep-service

# MongoDB Connection Configuration
spring.data.mongodb.uri=mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_resep?retryWrites=true&w=majority
spring.data.mongodb.database=db_ws_klinik_resep

spring.mongodb.uri=mongodb+srv://fellymonap:2243@clusterws.ljzabqs.mongodb.net/db_ws_klinik_resep?retryWrites=true&w=majority
spring.mongodb.database=db_ws_klinik_resep
